# Generated by Django 6.0.3 on 2026-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutset",
            name="weight",
            field=models.FloatField(help_text="Weight in lbs/kg"),
        ),
        migrations.AddIndex(
            model_name="workoutset",
            index=models.Index(
                fields=["workout", "exercise"], name="workouts_wo_workout_ca1c5c_idx"
            ),
        ),
    ]
