# Generated by Django 6.0.3 on 2026-03-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_alter_workoutset_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="biometrics",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
